#pragma config(UserModel, "C:/Users/rstudent/code/robot-configs/32B.c")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

#include <CKFlywheelSpeedController.h>


//#define trigger2power(BtnSet)  (vexRT[BtnSet ## U] ? 127 : (vexRT[BtnSet ## D] ? -127 : 0))

//if(vexRT[Btn6U]) motor[mIntakeVert] = 127;
//else if(vexRT[Btn6D]) motor[mIntakeVert] = -127;
//else



// Controller coefficients
const float Kq = 0.04, Kd = 0, Ki = 0.02;


FlywheelSpeedController ctlrL, ctlrR;

float targetSpeed = 0;


task FlywheelSpeedControl()
{
	while(true)
	{
		setTargetSpeed(ctlrL, targetSpeed);
		setTargetSpeed(ctlrR, targetSpeed);
		update(ctlrL);
		update(ctlrR);

		delay(60);
	}
}



void drive( int left, int right )
{
	motor[mDriveLB] = motor[mDriveLF] = left;
	motor[mDriveRB] = motor[mDriveRF] = right;
}


/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	const tMotor motorPortsL[] = {mFlyLF, mFlyLB};
	const tMotor motorPortsR[] = {mFlyRF, mFlyRB};

	//1.2762e0.138x
	FlywheelSpeedControllerInit( ctlrL, Kq, Ki, Kd, 1.2762, 0.138, motorPortsL, 2 );
	//1.2721e0.1416x
	FlywheelSpeedControllerInit( ctlrR, Kq, Ki, Kd, 1.2721, 0.1416, motorPortsR, 2 );
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	startTask(FlywheelSpeedControl);

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	startTask(FlywheelSpeedControl);

	float flywheelSpeed = 0;


	while (true)
	{
		drive( vexRT[Ch3], vexRT[Ch2] );

		motor[mIntakeFront] = vexRT[Btn6U] ? 127 : (vexRT[Btn6D] ? -127 : 0);
		motor[mIntakeVert] = vexRT[Btn5U] ? 127 : (vexRT[Btn5D] ? -127 : 0);

		if( vexRT[Btn7U] ){
			// Effectively turns on the flywheels, to the last speed used.
			targetSpeed = flywheelSpeed;
		} else if( vexRT[Btn7D] ){
			// Turns off the flywheels.
			targetSpeed = 0;
		}

		int speedUp = vexRT[Btn8U];
		int speedDown = vexRT[Btn8D];
		if( speedUp || speedDown )
		{
			if( speedUp ){
				flywheelSpeed += 1.0;
			}
			else {
				flywheelSpeed -= 1.0;
			}

			flywheelSpeed = bound(flywheelSpeed, 7, 11);
			targetSpeed = flywheelSpeed;
			delay(300);
		}

		delay(30);
	}
}
