#pragma config(UserModel, "C:/Users/rstudent/code/robot-configs/32B.c")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

#include <CKFlywheelSpeedController.h>


//#define trigger2power(BtnSet)  (vexRT[BtnSet ## U] ? 127 : (vexRT[BtnSet ## D] ? -127 : 0))



FlywheelSpeedController ctlrL, ctlrR;

bool isFlywheelOn = false;
const float MinFlyspeed = 16.;
const float MaxFlyspeed = 24.;
float targetFlywheelSpeed = MinFlyspeed;


task FlywheelSpeedControl() {
	while(true) {
		float spd = isFlywheelOn ? targetFlywheelSpeed : 0;

		setTargetSpeed(ctlrL, spd);
		setTargetSpeed(ctlrR, spd);
		update(ctlrL);
		update(ctlrR);

		delay(30);
	}
}



void setDrive( int left, int right ){
	motor[mDriveLB] = motor[mDriveLF] = left;
	motor[mDriveRB] = motor[mDriveRF] = right;
}


/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	const tMotor motorPortsL[] = {mFlyLF, mFlyLB};
	const tMotor motorPortsR[] = {mFlyRF, mFlyRB};

	const float Kq = 0.06, Ki = 0.02, Kd = 0;

	FlywheelSpeedControllerInit( ctlrL, Kq, Ki, Kd, 1.2908, 0.0602, motorPortsL, 2, M393Turbo );
	FlywheelSpeedControllerInit( ctlrR, Kq, Ki, Kd, 1.4517, 0.0560, motorPortsR, 2, M393Turbo );
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous() {
	startTask(FlywheelSpeedControl);
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////


task usercontrol() {
	startTask(FlywheelSpeedControl);

	time1[T1] = 0;

	while (true) {
		setDrive( vexRT[ChJoyLY], vexRT[ChJoyRY] );

		motor[mIntake] = buttonGroupToPower(Btn5);
		motor[mPuncher] = buttonToPower(Btn6U);

		if( vexRT[Btn7U] ){
			isFlywheelOn = true;
		} else if( vexRT[Btn7D] ){
			isFlywheelOn = false;
		}

		int speedUp = vexRT[Btn8U];
		int speedDown = vexRT[Btn8D];
		if( (speedUp || speedDown) && time1[T1] > 500 ){
			float delta = speedUp ? 0.5 : -0.5;
			targetFlywheelSpeed = bound( targetFlywheelSpeed + delta, MinFlyspeed, MaxFlyspeed );
			time1[T1] = 0;
		}

		delay(10);
	}
}
